[env:heltec_wifi_lora_32_V2]
platform = espressif32
board = heltec_wifi_lora_32_V2
framework = arduino
monitor_speed = 115200

build_flags =
    -D REGION_US915
    -D ACTIVE_REGION=LORAMAC_REGION_US915
    -D MONITOR_SPEED=115200

lib_deps =
    heltecautomation/Heltec ESP32 Dev-Boards @ ^1.1.2
    adafruit/DHT sensor library @ ^1.4.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    https://github.com/claws/BH1750.git